export enum FileSubmissionEvent {
  CREATED = '[FILE SUBMISSION] CREATED',
  REMOVED = '[FILE SUBMISSION] REMOVED',
  VERIFIED = '[FILE SUBMISSION] VERIFIED',
  SUBMISSIONS_VERIFIED = '[FILE SUBMISSIONS] VERIFIED',
}
