import { SubmissionRating } from 'src/submission/enums/submission-rating.enum';

export interface SubmissionPart<T extends DefaultOptions> {
  _id?: string; // autogenerated
  id: string;
  data: T;
  accountId: string;
  submissionId: string;
  website: string;
  isDefault?: boolean;
}

export interface Parts {
  [key: string]: SubmissionPart<any>;  // key is part.accountId
}

export interface DefaultOptions {
  title?: string | undefined;
  tags: TagData;
  description: DescriptionData;
  rating: SubmissionRating;
  useThumbnail: boolean;
}

export interface TagData {
  extendDefault: boolean;
  value: string[];
}

export interface DescriptionData {
  overwriteDefault: boolean;
  value: string;
}
