import { SubmissionType } from 'src/submission/enums/submission-type.enum';

export interface Submission {
  _id?: string; // autogenerated
  created: number;
  id: string;
  isPosting?: boolean;
  order: number;
  schedule: SubmissionSchedule;
  title: string;
  type: SubmissionType;
}

export interface SubmissionSchedule {
  isScheduled?: boolean;
  postAt?: number;
}
