import { DefaultOptions } from './default-options.interface';

export interface SubmissionPart<T extends DefaultOptions> {
  _id?: string; // autogenerated
  id: string;
  data: T;
  accountId: string;
  submissionId: string;
  website: string;
  isDefault?: boolean;
  postedTo?: string;
  postStatus?: 'SUCCESS' | 'FAILED' | 'UNPOSTED';
}

export interface Parts {
  [key: string]: SubmissionPart<any>; // key is part.accountId
}
