name: Build/Release
on:
  push:
    branches:
      - 'master'
      - 'develop'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 16

        # Note: These flags needed to speed up build
      - name: Install dependencies
        run: npm install --frozen-lockfile --prefer-offline

      - name: Build dependencies
        run: npm run make

      - name: Build/release Electron app (macOS)
        if: matrix.os == 'macos-latest'
        uses: samuelmeuli/action-electron-builder@v1
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_IDENTITY_AUTO_DISCOVERY: true
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ github.ref == 'refs/heads/master' }}
          skip-build: true
          app_root: 'electron-app'

      - name: Build/release Electron app (Windows/Linux)
        if: matrix.os != 'macos-latest'
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ github.ref == 'refs/heads/master' }}
          skip-build: true
          app_root: 'electron-app'
